version: "3.9"
services:
  whm:
    build: .
    container_name: whm
    environment:
      - PORT=3000
      - NODE_ENV=production
      - VIRTUAL_HOST=antonwy.me
      - VIRTUAL_PORT=3000
      - NEXT_PUBLIC_API_URL=https://api.antonwy.me
      - NEXT_PUBLIC_WEBSITE_URL=https://antonwy.me
    ports:
      - 3000:3000
    networks:
        - reverse-proxy-net

networks:
  reverse-proxy-net:
    name: reverse-proxy-net
    external: true